name: ci-sonarcloud
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up --build -d
      - name: Test ls
        run:  ls
      - name: Test ps
        run: docker exec micro-videos-app ls
      - name: Test
        run: docker exec micro-videos-app ./vendor/bin/phpunit
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
