name: ci-sonarcloud
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: change folder permission
        run: mkdir bootstrap/cache/
      - name: change folder permission
        run: sudo chmod -R 777 .
      - name: change folder permission
        run: sudo chmod -R 777 bootstrap/cache/
      - name: Build the stack
        run: docker-compose up --build -d
      - name: Test compose install
        run: docker exec micro-videos-app composer install
      - name: execute tests
        run: docker exec micro-videos-app ./vendor/bin/phpunit
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
